### ISSUE TITLE
Is it possible to get a frequency of function definition/usage?

### ISSUE THREAD

**Issue by timothypratley** [fbellomi/crossclj#10]
I'd like to be able to see how often functions are used/defined in the wild, can I get this info from crossclj?

**Comment by fbellomi** [comment]
If you click on the blue links (var usages) you jump to var definitions.

If you click on the yellow links (var definitions) you jump to the list of usages across all the indexed projects, 
for example this is for hiccup.core/html
https://crossclj.info/fun/hiccup.core/html.html

let me know if this solves your problem

**Comment by timothypratley** [comment]
Hi Francesco,


I'm trying to create a table of
function        used
dissoc-in      28
transpose    10
flatten1         5

Is there any way for me to get this from crossclj without clicking through every word?


Regards,
Timothy

**Comment by fbellomi** [comment]
Not directly, but I think you can easily write a small crawler that get this information:

you can use

(slurp "https://crossclj.info/fun/" namespace "/" var ".html")

and the find the substring "found in X defs" in the returned string, to programmatically find the number of global use for a given var. You can do that for all the vars in a ns, and so on.

Hope this helps

Francesco

**Comment by fbellomi** [comment]
Sorry, of course che correct syntax is

(slurp (str "https://crossclj.info/fun/" namespace "/" var ".html"))

and var needs to be url-encoded

Francesco

**Comment by timothypratley** [comment]
Thanks for the suggestions.
