### ISSUE TITLE
with-meta var in clojure.core does not show up in VARS list

### ISSUE THREAD

**Issue by jfacorro** [fbellomi/crossclj#7]
I may be doing something wrong, but is it possible that Vars defined using `def` that have a metadata map associated are not being listed in the VARS sections and are not returned in the search?

For an example of this behavior see [clojure.core](https://crossclj.info/ns/org.clojure/clojure/1.8.0-alpha5/clojure.core.html). Also trying to search `with-meta` doesn't return `clojure.core`s function as a possible result.

Awesome project!

**Comment by fbellomi** [comment]
Thanks for the feedback, I'll have a look.

**Comment by fbellomi** [comment]
The bug should be fixed now. 
Correct results should appear on the site as the next indexing cycle completes, ie. in the next 24 hours.
Thanks again for your bug report.

**Comment by jfacorro** [comment]
@fbellomi Thank you for fixing this. :smile:
